export type ORDER_SHEET_KEY_MAP_Type = {
    source: string,
    outgoingFileName: string,
    id: string,
    movementType: string,
    orderSheetType: string,
    orderId:  string,
    relativerProductId:  string,
    orderName:  string,
    outgoingProductName: string,
    outgoingProductCode:  string,
    outgoingProductId:  string,
    orderCount: string,
    orderUnit:  string,
    outgoingProductCount: string,
    outgoingContainerName:  string,
    outOfStockYype:  string,
    changeCount: string,
    outgoingProductCancel:  string,
    orderInfoId:  string,
    outgoingOrderCancled:  string,
    ordererName:  string,
    ordererPhone:  string,
    receiverName:  string,
    receiverPhone1:  string,
    receiverPhone2:  string,
    receiverAddress1:  string,
    receiverAddress2: string,
    memo: string,
    courier:  string,
  };
  