export const ORDER_REVERSE_SHEET_KEY_MAP = {
  '데이터 출처': 'source',
  '출고서 파일명': 'outgoingFileName',
  '엑셀 행 순번': 'id',
  '이동 상태': 'movementType',
  '주문서 양식': 'orderSheetType',
  '주문서 번호': 'orderId',
  연동상품ID: 'relativerProductId',
  주문명: 'orderName',
  출고상품명: 'outgoingProductName',
  출고상품코드: 'outgoingProductCode',
  출고상품: 'outgoingProductId',
  주문수량: 'orderCount',
  주문단위: 'orderUnit',
  출고수량: 'outgoingProductCount',
  출고창고명: 'outgoingContainerName',
  재고부족여부: 'outOfStockYype',
  수량변경: 'changeCount',
  '출고취소(상품)': 'outgoingProductCancel',
  주문정보ID: 'orderInfoId',
  '출고취소(주문)': 'outgoingOrderCancled',
  주문자: 'ordererName',
  주문자전화번호: 'ordererPhone',
  수취인: 'receiverName',
  수취인전화번호1: 'receiverPhone1',
  수취인전화번호2: 'receiverPhone2',
  수취인주소1: 'receiverAddress1',
  수취인주소2: 'receiverAddress2',
  메모: 'memo',
  택배사명: 'courier',
};
